### ISSUE TITLE
Show nomination progress

### ISSUE THREAD

**Issue by usetech-llc** [usetech-llc/apps#20]
This section should display "In progress" after clicking "Start" button and "Completed" after nomination transactions are finalized. Also, after the "start" button is clicked, this button and amount input field need to be disabled.

![image](https://user-images.githubusercontent.com/29665644/81397359-d0c0ad00-912f-11ea-85aa-1b7c449a2cd2.png)

**Comment by kpozdnikin** [comment]
I've added a loader to the start button
