### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by kpozdnikin** [usetech-llc/apps#29]
https://www.figma.com/proto/bNrIhQAg5lyKPGocNm0Huh/kusama-nomination?node-id=30%3A52&viewport=718%2C478%2C0.29915890097618103&scaling=min-zoom

Page 1

“Start” => Bond and Nominate

Если на этом кошельке уже есть, то “Add funds” (название, а функция Bond More)

Где поставил коммент 3 нужно сверху поставить сумму на которую человек номинировал (“Bonded”) и текущую комиссию “Comission”, остальное внизу в логическом поряде (первым наверное “Total”, потом “Transferable”). А вот если у человека идет unbonding, то хорошо бы это показать сверху и рядом время оставшееся.

На оставшемся месте после кнопки Бонд можно поставить кнопку Notifications которая ведет на нужный телеграм канал

Page 3 Accounts с развернутым отчетом

Сначала надо показать Активную номинацию, потом неактивные а последней – waiting.

И Последнее – нам надо написать Help свой.

- [x] 1. add word Notification to telegram icon and move it on the top.

- [x] 2. Close window as option

- [x] 3. Checkout QR styles

- [x] 4. Scrollbar (auto)

- [x] 5. Separate states for current and new nomination

- [x] 6. Update nomination does't have event message

- [x] 7. Change title to Usetech Kusama Nomination and change favicon

- [x] Add "Manage nominations" button

- [x] Add "To new nomination" button

- [x] Save current step state into localStorage

- [x] Update current step state to "Manage nominations" when nominated successfully

- [x] Update help text with https://docs.google.com/document/d/1u0ncoX5Rs0qEudyazbN5MsghCurx-WqeGrQx42k27bA/edit

**Comment by usetech-llc** [comment]
If a wallet has an active nomination, then "Start" button (rename it to "Bond and Nominate" in basic use case) should be "Add funds" (with functionality of "Bond More", which too should be renamed to Add funds)
