### ISSUE TITLE
Text fixes

### ISSUE THREAD

**Issue by usetech-llc** [usetech-llc/apps#40]
- [x] <img width="946" alt="Screen Shot 2020-10-05 at 10 17 15 AM" src="https://user-images.githubusercontent.com/29665644/95050871-f52bb000-06f4-11eb-89af-fd06a52ccbf0.png">
Replace  "You have no enough balance for nomination" with "You do not have enough balance for nomination on this account, add funds or change the account".

- [x]  Replace "Warning: After bonding, your funds will be locked and will remain locked after the nomination is stopped for 100,800 blocks, which is approximately 7 days." with

"Warning: After bonding your funds you can stop the operation at any time, but your funds will remain locked for additional 7 days"

- [x]  Bond and Nominate screen does not fit the screen unless the screen is maximized, it's too big. Shrink by 20% or something similar.

- [x]  Slider start is not centered on open (it should be)

- [x] Replace "Now the 'Balanced strategy' is installed. If you change the candidates below, the strategy will become a 'Manual'" with: 1. In Automatic mode "Use slider to change the automatic strategy. If you change the candidates bellow, the strategy mode will switch to Manual." 

2. In Manual mode: "Add or remove candidates bellow. If you change the mode to Automatic, your current choices will remain in place until you move the slider."

- [x]  Manage Nomination screen - add tooltips for buttons

- [x]  Bond more funds screen - remove "Stash account" and "Since this transaction deals with funding, the stash account will be used.", replace help tips (Your account)

- [x]  Update nomination help tip opens only when clicking the button - add prevent (stop propagation)

- [x]  Stop nomination replace "Authorize transaction" with "Stop nominating" 

replace "The details of the transaction including the type, the description (as available from the chain metadata) as well as any parameters and fee estimations (as available) for the specific type of call.
The sending account that will be used to send this transaction. Any applicable fees will be paid by this account." with
"This operation only stops the nomination selection, it does not unbond your funds. You can use "Unbond" operation for that, or can choose "Update nomination" to make a new selection of validators".

- [x]  Ubnond funds replace with "Unbond funds", same for its help button.

**Comment by kpozdnikin** [comment]
Can you please add screenshots of this bugs:

1. Bond and Nominate screen does not fit the screen unless the screen is maximized, it's too big. Shrink by 20% or something similar.
2. Slider start is not centered on open (it should be).

**Comment by kpozdnikin** [comment]
Manage Nomination screen - add tooltips for buttons - for all buttons? Now there is only tooltip for "update nomination" button.
